-- MySQL Script generated by MySQL Workbench
-- Вт. 06 дек. 2016 17:17:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shop` ;

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  `salt` VARCHAR(255) NOT NULL COMMENT '',
  `status` ENUM('online', 'ofline', 'removed', 'banned') NOT NULL COMMENT '',
  `discount` INT(2) NULL DEFAULT NULL COMMENT '',
  `birthday` DATE NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `first_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `last_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `role` ENUM('CLIENT', 'ADMIN') NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  `image` BLOB NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`payment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`delivery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`order` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` INT UNSIGNED NOT NULL COMMENT '',
  `payment_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `delivery_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `comment` TEXT NULL DEFAULT NULL COMMENT '',
  `price` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_order_client_idx` (`user_id` ASC)  COMMENT '',
  INDEX `fk_order_payment1_idx` (`payment_id` ASC)  COMMENT '',
  INDEX `fk_order_delivery1_idx` (`delivery_id` ASC)  COMMENT '',
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `shop`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `shop`.`payment` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_delivery1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `shop`.`delivery` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`manufacturer` (
  `id` INT UNSIGNED NOT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  `logo` BLOB NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `category_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `manufacturer_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `description` TEXT NULL DEFAULT NULL COMMENT '',
  `price` INT NOT NULL COMMENT '',
  `keywords` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quantity_in_stock` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_product_category1_idx` (`category_id` ASC)  COMMENT '',
  INDEX `fk_product_manufacturer1_idx` (`manufacturer_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `shop`.`category` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_manufacturer1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `shop`.`manufacturer` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`order_product` (
  `order_id` INT UNSIGNED NOT NULL COMMENT '',
  `product_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`order_id`, `product_id`)  COMMENT '',
  INDEX `fk_order_has_product_product1_idx` (`product_id` ASC)  COMMENT '',
  INDEX `fk_order_has_product_order1_idx` (`order_id` ASC)  COMMENT '',
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `shop`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`product_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`product_image` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `product_id` INT UNSIGNED NOT NULL COMMENT '',
  `image` BLOB NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_product_image_product1_idx` (`product_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_image_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
